### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sfarkas1988** [Remixjobs/RjEmailBundle#16]
Hello, 

as i get right your bundle doesn't work without sonataAdminBundle but it's not documentatet in your documentation and not listed inside packagist.

Fatal error: Class 'Sonata\AdminBundle\Controller\CRUDController' not found 

Thanks for your help.

**Comment by jeremymarc** [comment]
Sonata is a dependencies of the project. We will change that soon. Sorry for the delay!
