### ISSUE TITLE
sent_email table not feed

### ISSUE THREAD

**Issue by salamichel** [Remixjobs/RjEmailBundle#18]
Hi, thank you for this bundle.
How to setup the module for log email sent ? 

I use this following code to sent an email (successfully) but the sent_email table do not store the content of email sent by application.

What's wrong,

bregards

$manager = $this->get('rj_email.email_template_manager');
        $message = \Rj\EmailBundle\Swift\Message::fromArray($manager->renderEmail("testing"));
        $message->setTo('xxxxl@gmail.com');
        $this->get('mailer')->send($message);

**Comment by makasim** [comment]
It has to be done by a listener: https://github.com/Remixjobs/RjEmailBundle/blob/master/Swift/Events/SendListener/MessageSendListener.php, added here: https://github.com/Remixjobs/RjEmailBundle/blob/master/Resources/config/services.xml#L52

It has to be work out of the box, but I am not sure.  Do you see any exceptions or something in the log files?

**Comment by salamichel** [comment]
Hi, thank you for your reply.

I'm OK that should be done by the listener, but it seems not triggered. With the profiler bar in event section, I do not have any corresponded events.

I do not have any errors or exceptions

**Comment by salamichel** [comment]
arg ticket is not closed

**Comment by makasim** [comment]
@salamichel you still able to reopen it.

**Comment by salamichel** [comment]
How to move forward about this topic ?  I'm on symfony 2.3.16, the email is correctly send. I do not understand why the service "rj_email.message_send_listener" is not triggered.

Do you have any suggestion ?

Best regards

This is the log of _Not Called Listeners_

Event name  Listener
console.terminate    EmailSenderListener::onTerminate
kernel.exception     ExceptionListener::onKernelException
kernel.exception     ProfilerListener::onKernelException
kernel.exception     ExceptionListener::onKernelException
kernel.terminate     PostponeRuntimeBackend::onEvent
kernel.terminate     EmailSenderListener::onTerminate
kernel.view  ViewResponseListener::onKernelView
knp_pager.before     FiltrationSubscriber::before
knp_pager.before     PaginationSubscriber::before
knp_pager.before     SortableSubscriber::before
knp_pager.pagination     SlidingPaginationSubscriber::pagination
knp_pager.pagination     PaginationSubscriber::pagination
security.interactive_login   InteractiveLoginListener::onSecurityInteractiveLogin
security.interactive_login   InteractiveLoginListener::onSecurityInteractiveLogin
sonata.notification.event.message_iterate_event  DoctrineOptimizeListener::iterate

**Comment by salamichel** [comment]
Hi,  did it works on your configuration ? I'm quite sure something is missing.
i'm using swiftmailer 4.3

**Comment by makasim** [comment]
it has to be, I dont have a chance to tests it.
